# -*- coding: utf-8 -*-
"""st.py — minimal safetensors reader/writer (pure numpy, no dependencies).

Format: 8-byte LE u64 header length N, then N bytes JSON header
{name: {"dtype": ..., "shape": [...], "data_offsets": [start, end]}},
then the raw tensor data. Header is padded to 8-byte alignment.
F16/BF16 can be auto-upcast to F32 for our FP32 compute shaders.
"""
import json
import struct

import numpy as np

_TO_NP = {
    "F64": np.float64, "F32": np.float32, "F16": np.float16,
    "I64": np.int64, "I32": np.int32, "I16": np.int16, "I8": np.int8,
    "U8": np.uint8,
}
_FROM_NP = {v: k for k, v in _TO_NP.items()}


def load_file(path, upcast_float32=True):
    """Load a .safetensors file -> {name: np.ndarray}.

    BF16 is always converted to F32 (numpy has no native bfloat16).
    F16 is converted to F32 when upcast_float32=True.
    """
    with open(path, "rb") as f:
        n = struct.unpack("<Q", f.read(8))[0]
        header = json.loads(f.read(n))
        data = f.read()
    out = {}
    for k, v in header.items():
        if k == "__metadata__":
            continue
        dt_name, shape = v["dtype"], v["shape"]
        s, e = v["data_offsets"]
        if dt_name == "BF16":
            u = np.frombuffer(data, dtype=np.uint16, count=(e - s) // 2, offset=s).astype(np.uint32)
            out[k] = (u << 16).view(np.float32).reshape(shape)
            continue
        dt = _TO_NP[dt_name]
        cnt = (e - s) // np.dtype(dt).itemsize
        arr = np.frombuffer(data, dtype=dt, count=cnt, offset=s).reshape(shape)
        if upcast_float32 and dt == np.float16:
            arr = arr.astype(np.float32)
        out[k] = arr
    return out


def save_file(tensors, path, metadata=None):
    """Save {name: np.ndarray} -> .safetensors file."""
    header = {}
    blobs = []
    offset = 0
    for name, arr in tensors.items():
        arr = np.ascontiguousarray(arr)
        dt_name = _FROM_NP.get(arr.dtype.type)
        if dt_name is None:
            raise TypeError(f"unsupported dtype for safetensors: {arr.dtype}")
        header[name] = {"dtype": dt_name, "shape": list(arr.shape),
                        "data_offsets": [offset, offset + arr.nbytes]}
        blobs.append(arr.tobytes())
        offset += arr.nbytes
    header["__metadata__"] = metadata or {"format": "vkops", "note": "generated by vkops"}
    hb = json.dumps(header, separators=(",", ":")).encode("utf-8")
    hb += b" " * ((8 - len(hb) % 8) % 8)
    with open(path, "wb") as f:
        f.write(struct.pack("<Q", len(hb)))
        f.write(hb)
        for b in blobs:
            f.write(b)
